//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMTrail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public Nullable<int> id { get; set; }
        public string name { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
